export const FETCH_ALBUMS = "FETCH_ALBUMS";
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT";
export const LOADING = "LOADING";
export const SAVE_TO_FAVORITE = "SAVE_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const SERVER_ERROR = "SERVER_ERROR";

